# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30486c2cccd48e9ccd4862e57e1ce0f13d548083d10248db5d03c607408bf1018aa321863156c3e252ef846d8631694e424c53a4b92523dbfd0f5242425cad07

test:
  secret_key_base: b8299a4fefda5063822c1636b09b43919f674918daf59e55fda61d027c896547b3438eadf81c0e305d93309f5f82a68d5f456888eb184e55d336028f3b0aeff8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
